sequenceDiagram
    participant PEP
    participant PAP
    participant PIP
    participant PDP
    participant Decision Log
    PAP->>PDP: Policies
    PIP->>PDP: Static information
    PEP->>PDP: Access Evaluation Request
    PDP->>+PIP: Dynamic information
    PIP-->>-PDP: ack
    PDP->>+Decision Log: Log Record
    Decision Log-->>-PDP: ack
    PDP->>PEP: Decision